application: kudosenglishlearning
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /html5-boilerplate
  static_dir: html5-boilerplate
- url: /i
  static_dir: i
- url: /js
  static_dir: js
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /.*
  script: main.py
