application: helloworld
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /html5-boilerplate
  static_dir: html5-boilerplate
- url: /i
  static_dir: i
- url: /.*
  script: main.py
